---

- name: Configurar Switch Este
  hosts: sw-este
  gather_facts: false
  connection: local
  
  roles:
    - config_sw_este

- name: Configurar Switch Oeste
  hosts: sw-oeste
  gather_facts: false
  connection: local
  
  roles:
   - config_sw_oeste

- name: Configurar Router Oeste
  hosts: r-oeste
  gather_facts: false
  connection: local

  roles:
    - config_r_oeste

- name: Configurar Router Norte
  hosts: r-norte
  gather_facts: false
  connection: local

  roles:
    - config_r_norte

- name: Realizar copia de seguridad
  hosts: all
  gather_facts: false
  connection: local

  roles:
    - Backup
