## Configure the router's interfaces ##

---

- include_vars: ../vars/main.yml         
- name: Enable serial 0/1/1
  ios_interface:
    authorize: yes
    auth_pass: ansible
    name: Serial 0/1/1
    description: to r-norte

- name: Configure serial 0/1/1
  ios_config:
    authorize: yes
    auth_pass: ansible
    lines:
      - ip address {{ ips60 }} {{ mask_r_oeste_s6_0 }}
      - clock rate 128000
    parents:
      - interface {{ item.id }}

    after: no shutdown

  with_items:
    - { id: Serial 0/1/1 }

- name: Save configuration
  ios_command:
    authorize: yes
    auth_pass: ansible
    commands:
      - write memory
