---

#Force trunking on Interface f0/2#

- name: Enable and describe f0/2
  ios_interface:
    authorize: yes
    auth_pass: ansible
    name: f0/2
    description: trunk port

- name: Enable trunk mode on f0/2
  ios_config:
    authorize: yes
    auth_pass: ansible
    lines:
      - switchport mode trunk
      - switchport trunk native vlan 99
    parents:
      - interface FastEthernet 0/2


####Assign f0/3 to VLAN 23#####
- name: Enable, describe f0/3
  ios_interface:
    authorize: yes
    auth_pass: ansible
    name: f0/3
    description: Access to Vlan 23

- name: Enable mode access on int f0/3
  ios_config:
    authorize: yes
    auth_pass: ansible
    lines:
      - switchport mode access
      - switchport access vlan 23
    parents:
      - interface FastEthernet 0/3

###Assign all other ports as access ports and Shutdown####

- name: Modo access para las demás interfaces & Shutdown interfaces
  ios_config:
    authorize: yes
    auth_pass: ansible
    lines: 
      - switchport mode access
    parents: 
      - interface range {{ item.name }}
    after:
      - shutdown
  
  with_items:
    - { name: FastEthernet 0/4 - 24 }
    - { name: GigabitEthernet 0/2 }

- name: Show Running Config
  ios_command:
    authorize: yes
    commands:
      - show run | begin interface

  register: sh_run_interface

- debug: var=sh_run_interface.stdout_lines

- name: save running to startup when modified
  ios_config:
    authorize: yes
    auth_pass: ansible
    save_when: modified

