
---

#Force trunking on Interface G0/0 with r-oeste#

- name: Enable and describe f0/1 r-oeste
  ios_interface:
    authorize: yes
    auth_pass: ansible
    name: f0/1
    description: trunk port with r-oeste

- name: Enable trunk mode on f0/1 r-oeste
  ios_config:
    authorize: yes
    auth_pass: ansible
    lines:
      - switchport mode trunk
      - switchport trunk native vlan 1
    parents:
      - interface FastEthernet 0/1


####Assign G3/3 to VLAN 21#####

- name: Enable, describe f0/3 vlan 21
  ios_interface:
    authorize: yes
    auth_pass: ansible
    name: f0/3
    description: Access to Vlan 21

- name: Enable mode access on int f0/3 vlan 21
  ios_config:
    authorize: yes
    auth_pass: ansible
    lines:
      - switchport mode access
      - switchport access vlan 21
    parents:
      - interface FastEthernet 0/3

###Assign all other ports as access ports and Shutdown####

- name: Modo access para las demás interfaces & Shutdown interfaces
  ios_config:
    authorize: yes
    auth_pass: ansible
    lines: 
      - switchport mode access
    parents: 
      - interface range {{ item.name }}
    after:
      - shutdown
  
  with_items:
    - { name: FastEthernet 0/4 - 24 }

- name: Show Running Config
  ios_command:
    authorize: yes
    commands:
      - show run | begin interface

  register: sh_run_interface

- debug: var=sh_run_interface.stdout_lines

- name: save running to startup when modified
  ios_config:
    authorize: yes
    auth_pass: ansible
    save_when: modified





