---
- include_vars: ../vars/main.yml
- name: Enable OSPF on R-norte
  ios_config:
    authorize: yes
    auth_pass: ansible
    lines:
      - network {{ ip_lanS6_1 }} {{ wildmask_lanS6_1 }} area 1
    parents:
      - router ospf 1
